version: "3.3"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsapp-clone
    ports: 
      - 5000:5432 
  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 6379:6379
  server: 
    build: ./server
    restart: always
    depends_on:
      - db
      - cache
    ports:
      - 4000:4000


