import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import styled from "styled-components";

import ChatSection from "../components/ChatSection";
import Sidebar from "../components/Sidebar";
import { isUserLoggedIn } from "../utils/isUserLoggedIn";
import { User } from "../generated/graphql";
import { ChatProvider } from "../context/ChatContext";
import { NewMessageProvider } from "../context/NewMessageContext";
import { useUser } from "../context/UserContext";

const Container = styled.div`
  display: flex;
  height: 100vh;
  width: 100vw;
`;

const SidebarContainer = styled.div`
  width: 100%;
  height: 100%;
  flex: 40%;
  min-width: 330px;
  border-right: 1px solid ${({ theme }) => theme.globalTheme.greyLineColor};
  ${({ theme }) => theme.homePageTheme.mediumScreen`
    flex: 35%;
  `};
`;

interface HomePageProps {
  currentUser: User;
}

const Home: NextPage<HomePageProps> = ({ currentUser }) => {
  const { setUser } = useUser();
  useEffect(() => {
    if (setUser) {
      setUser(currentUser);
    }
  }, [currentUser, setUser]);

  return (
    <div>
      <Head>
        <title>Whatsapp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChatProvider>
        <NewMessageProvider>
          <Container>
            <SidebarContainer>
              <Sidebar />
            </SidebarContainer>
            <ChatSection />
          </Container>
        </NewMessageProvider>
      </ChatProvider>
    </div>
  );
};

export const getServerSideProps = isUserLoggedIn;

export default Home;
