export const globalTheme = {
  iconColor: "#51585c",
  primaryGrey: "#EDEDED",
  searchBarColor: "#f6f6f6",
  greyFontColor: "#999999",
  greyLineColor: "#e4e4e4",
  greyMessageColor: "rgba(0,0,0,0.6)",
  selectGrey: "#ebebeb",
  chatScreenBackground: "#e5ddd5",
  chatBoxBackground: "#f0f0f0",
  readBlueCheck: "#4fc3f7",
  greyCheck: "#a4a4a4",
  messageGreen: "#dcf8c6",
  registerBackgroundGrey: "#f8f9fa",
  white: "#fff",
};
